language: c++
sudo: required
dist: trusty

compiler:
  - gcc
  
python:
  - "2.7"

install:
  - sudo pip2 install lizard -q # Cyclomatic Complexity Check Tool
  - sudo update-alternartives --install /usr/bin/g++ g++ /usr/bin/g++-5 90

addons:
  apt:
    sources:
      # add PPAs with more up-to-date toolchains
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - cmake
      - valgrind
      - gcc-5

before_script:
  - gcc --version
  - python --version
  - cmake --version
  - valgrind --version
  - lizard --version

script: 
  - source .fetch-build-environment.sh ~/build-environment
  - source test.sh
